version: '3.8'
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  mafia-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 50051:50051
    networks:
      - mafia-network

  mafia-client-bot:
    build:
      context: .
    command: --role client --bot
    networks:
      - mafia-network

networks:
  mafia-network:
    name: "mafia-network"

