# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.grpc import schema_pb2 as app_dot_grpc_dot_schema__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/mafia.Greeter/Ping',
                request_serializer=app_dot_grpc_dot_schema__pb2.PingRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_schema__pb2.PingReply.FromString,
                )
        self.StreamPing = channel.unary_stream(
                '/mafia.Greeter/StreamPing',
                request_serializer=app_dot_grpc_dot_schema__pb2.PingRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_schema__pb2.PingReply.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=app_dot_grpc_dot_schema__pb2.PingRequest.FromString,
                    response_serializer=app_dot_grpc_dot_schema__pb2.PingReply.SerializeToString,
            ),
            'StreamPing': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPing,
                    request_deserializer=app_dot_grpc_dot_schema__pb2.PingRequest.FromString,
                    response_serializer=app_dot_grpc_dot_schema__pb2.PingReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mafia.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mafia.Greeter/Ping',
            app_dot_grpc_dot_schema__pb2.PingRequest.SerializeToString,
            app_dot_grpc_dot_schema__pb2.PingReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamPing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mafia.Greeter/StreamPing',
            app_dot_grpc_dot_schema__pb2.PingRequest.SerializeToString,
            app_dot_grpc_dot_schema__pb2.PingReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
